listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    allow_reuse     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain     on;
    allow_reuse     on;
}

rtc_server {
    enabled         on;
    listen          8000;
    candidate       $CANDIDATE;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path       ./objs/nginx/html;
        hls_fragment   2;
        hls_window     6;
        hls_cleanup    on;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }

    play {
        gop_cache_max_frames 2500;
        queue_length 10;
    }

    security {
        enabled off;
    }
}
